# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the application's dependencies
RUN npm ci

# Copy the application source code to the container
COPY . .

# Build the application
RUN npm run build


# Start the application
CMD ["node", "./dist/main.js"]
